# Generated by Django 4.0.3 on 2022-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('credit_class', models.IntegerField()),
                ('total_slot', models.IntegerField()),
                ('remain_slot', models.IntegerField()),
                ('period', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('classroom', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
            ],
        ),
    ]
